name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  carousel_slider: ^4.2.1
  styled_divider: ^1.0.5
  iconify_flutter: ^0.0.5
  smooth_page_indicator: ^1.2.0+3
  get_storage: ^2.1.1
  calender_picker: ^2.0.2
  restart_app: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
  
  fonts:
    - family: DM san
      fonts:
        - asset: assets/fonts/DMSans-VariableFont_opsz,wght.ttf
    - family: Raleway
      fonts: 
        - asset: assets\fonts\Raleway-VariableFont_wght.ttf
          
